//
//  Data.swift
//  Scuba
//
//  Created by Lyes BOUKBOUKA on 10/11/2020.
//
import SwiftUI
import Foundation

extension Color {
    static let colorFlore = Color("colorFlore")
    static let colorVestige = Color("colorVestige")
    static let colorParcours = Color("colorParcours")
    static let colorFaune = Color("bluescuba")
}

enum DetailElement: String, CaseIterable {
    case description = "Description"
    case avis = "Avis"
    case localisation = "Localisation"
    
    
    static var allDetail: [String] {
        Self.allCases.map{ $0.rawValue }
    }
}

struct Espece : Identifiable {
    var id = UUID()
    var title: String
    var latitude: Double
    var longitude: Double
    var subTitle: String
    var pic: String
    var type: Type
    var fav: Bool
    var lieu: String
    var desc: String
}

enum Type: String, CaseIterable {
    
    case tous = "Tous", faune = "Faune", flore = "Flore", vestige = "Vestige", parcours = "Parcours"
}

struct DataEspece {
    
    static var especes = [

        Espece(title: "Dauphin", latitude: 43.360109, longitude: 8.182452, subTitle: "Tursiops truncatus", pic: "dauphin", type: .faune, fav: true, lieu:"Large de la Meditérranée", desc: "Le grand dauphin également appelé souffleur, dauphin à gros nez ou tursiops (Tursiops truncatus) est un cétacé à dents (odontocète) appartenant à la famille des Delphinidae. C'est l'espèce la mieux connue de sa famille, notamment parce qu'elle a été longuement étudiée en captivité et, à l'état naturel, le long des côtes qu'elle fréquente.\n\nC'est aussi l'une des rares espèces de dauphins à pouvoir survivre pendant un temps aux conditions de vie controversées des delphinariums. C'est celle que le grand public associe généralement aux dauphins (surtout grâce à la série télévisée Flipper le dauphin). On la reconnaît à son « sourire » assez caractéristique, dû aux plis de son rostre. Le grand dauphin est présent dans toutes les mers du monde, à l'exception des zones arctiques et antarctiques. Il existe deux populations assez distinctes : une côtière et une pélagique. Les grands dauphins chassent en utilisant leur capacité d'écholocalisation. Ils se nourrissent principalement de poissons qu'ils saisissent grâce à une centaine de petites dents pointues non différenciées.\n\nLes dauphins communiquent grâce à une variété de sons émis par l'intermédiaire du melon, un sac nasal situé sur le front. Ils atteignent la maturité sexuelle vers l'âge de 12 ans. Les femelles donnent naissance à un seul petit par portée. Les grands dauphins vivent généralement en groupe formé des femelles et des jeunes, alors que les mâles forment des associations appelées alliances. C'est un animal qui montre une certaine curiosité lors de ses rencontres avec des humains."),
        
        
        
        Espece(title: "Rascasse", latitude: 43.264182, longitude: 8.094562 , subTitle: "Pterois volitans", pic: "rascasse", type: .faune, fav: true, lieu: "Côtes rocheuse", desc: "Le mot rascasse est un nom vernaculaire ambigu en français, pouvant désigner plusieurs espèces différentes de poissons réparties dans plusieurs genres, principalement de la famille des scorpaenidés.\n\nCe sont dans l'ensemble surtout des poissons de fonds rocheux au corps massif avec des lambeaux de peau, aux nageoires épineuses ainsi que la tête, elle-même dotée d'une large bouche. Ils sont appelés aussi crapauds de mer ou scorpions de mer. Plusieurs de ces poissons de mer sont comestibles et d'ailleurs commercialisés. D'autres espèces, comme les rascasses volantes, sont toutefois très venimeuses de par leurs rayons piquants et chargés de venin, quoique comestibles.\n\nC'est un poisson commun, migrateur, qui vit en solitaire ou en petits groupes autour des récifs marins, et est actif la nuit ou au crépuscule. La rascasse volante se nourrit principalement de poissons de moins de 15 cm en général mais également de petits crustacés et de petits mollusques. Il semblerait qu'elle devienne de plus en plus piscivore en grandissant." ),
        
        
        
        Espece(title: "Castagnole rouge", latitude: 43.316161, longitude: 6.891559, subTitle: "Apogon imberbis", pic: "castagnole", type: .faune, fav: false, lieu:"Près du rivage ", desc: "L'Apogon (Apogon imberbis), aussi appelé Castagnole rouge, Coq, Poisson-cardinal ou Roi des rougets est une espèce de poissons de la famille des Apogonidae. Reconnaissable par sa coloration rouge orangée, par ses gros yeux noirs barrée de deux stries blanches, ce poisson habite sur les côtes méditerranéennes ainsi que sur les côtes de l'Atlantique est, du sud de la France jusqu'au golfe de guinée.\n\nIl habite aussi les côtes des iles des Açores, du Cap-Vert et des îles Canaries. Craintif, ce poisson habite dans les anfractuosités rocheuses ainsi que dans les grottes et les cavités naturelles ou artificielles, comme l'intérieur des épaves. La nuit, il devient actif et cherche sa nourriture. Macrophage, zoophage et carnassier, il se nourrit de petits poissons et d'invertébrés."),
        
        Espece(title: "Sardine", latitude: 43.545537, longitude: 7.160724, subTitle: "Sardina pilchardus", pic: "sardine", type: .faune, fav: true, lieu:"Partout dans la meditérranée", desc: "La sardine, Sardina pilchardus est une espèce de poissons de la famille des clupéidés qui comprend également le hareng, l'alose, notamment. Selon la région, elle prend les noms de célan, célerin, pilchard, royan, sarda, sardinyola.\nMesurant au plus une vingtaine de centimètres de long, la sardine possède un ventre argenté et un dos bleuté. Elle se caractérise par : \nun opercule strié,\ndes taches sombres sur le dos,\nune carène ventrale peu aigüe,\ndes écailles sessiles,\nles deux derniers rayons de l’arête anale plus longs."),
        
        Espece(title: "Posidonie", latitude: 43.388059, longitude: 6.814655, subTitle: "Posidonia oceanica", pic: "posidonie", type: .flore, fav: true, lieu:"Au bord du rivage mais aussi près des côtes", desc: "Les posidonies (du genre Posidonia) sont des plantes aquatiques de la famille des Posidoniaceae. Bien qu'elles vivent sous l'eau, ce ne sont pas des algues, mais des plantes à fleurs (angiospermes) monocotylédones sous-marines.\n\nComme toutes les plantes à fleurs, elles ont des racines, et se reproduisent grâce aux fruits qu'elles produisent. Dans les eaux moins chaudes de l'Atlantique nord européen, elles sont remplacées par les zostères qui constituent des herbiers jouant les mêmes fonctions écologiques.\n\nLes fibres des feuilles de posidonies, difficilement dégradables, sont rassemblées par les mouvements de la mer en boule feutrées, appelées aegagropiles, souvent rejetées sur les plages de Méditerranée, dont elles constituent une espèce endémique. Le nom générique Posidonia dérive de « Poséidon » dieu des Mers et des Océans dans la mythologie grecque." ),
        
        Espece(title: "Carpodesima", latitude: 42.967453 , longitude: 6.452106, subTitle: "Carpodesmia mediterranea", pic: "carpodesmia", type: .flore, fav: false, lieu:"Au bord du rivage mais aussi près des côtes", desc: "Carpodesmia mediterranea (basionyme : Cystoseira mediterranea) est une espèce d’algues brunes de la famille des Sargassaceae, endémique des côtes de la mer Méditerranée.\n\nElle se développe près de la surface, en milieux battus."),
        
        Espece(title: "Mérou brun", latitude:  41.872604, longitude: 6.380695, subTitle: "Epinephelus marginatus", pic: "merou", type:.faune , fav:false, lieu: "Côtes rocheuse", desc: "Le Mérou brun (Epinephelus marginatus), aussi appelé mérou de Méditerranée, mérou noir, mérou rouge ou mérou sombre est une espèce de poissons. Il fait partie des huit espèces de mérous recensées dans la Méditerranée de la famille des Serranidae mais on le trouve aussi au Brésil.Son corps est ovale et massif, couvert de petites écailles. La tête est épaisse et porte des yeux proéminents, entourés de taches claires.\n\nCe poisson porte une nageoire dorsale unique, et a une queue arrondie à bordure blanche. Les nageoires pectorales et anales s'assombrissent distalement. Cette espèce peut atteindre 150 cm pour 100 kg.\n\nSon espérance de vie moyenne est de 50 ans.Ce poisson vit entre 20 et 200 mètres de profondeur, près du fond, dans les zones rocheuses accidentées. On le trouve dans toute la Méditerranée." ),
        
        Espece(title: "Padine queue de paon", latitude: 41.665706, longitude: 8.761981, subTitle: "Padina pavonica", pic: "padine", type: .flore, fav: false, lieu:"Au bord des côtes", desc:"Padina pavonica, la Padine Queue-de-paon, est une espèce d'algues brunes de la famille des Dictyotaceae. Les thalles sont blanchis par le calcaire qu'il contiennent formant des cercles concentriques. Leur taille peut varier entre 5 et 10 cm. Abondante au printemps, cette algue s'accommode d'un réchauffement et d'un éclairage intense.\n\nElle est sensible aux variations de niveau d'eau (l'étiage, en particulier pour les bas niveau d'eau) et ne peut supporter que de très brèves expositions à l'air libre. Les individus sont souvent groupés autour d'un même système basal rampant. Des recherches scientifiques auraient montré que la Padina pavonica a des propriétés rappelant celles de la peau humaine jeune. Ainsi, utilisée en pharmacie et en cosmétique, elle favoriserait le renouvellement de ces glycosaminoglycanes (molécules très hydrophiles du derme responsables de la fermeté et de l'élasticité de la peau ; leur synthèse diminue avec l'âge) et renforcerait leurs actions protectrices (anti-radicalaires et anti-irritantes) et leurs actions sur le maintien de la vitalité cellulaire (fermeté et souplesse de la peau).\n\nElle trouverait également son emploi dans des traitements contre des affections osseuses telles l'ostéoporose, l'arthrite et par conséquent, serait utilisée dans des substituts alimentaires à base de calcium. Enfin, récoltée à la main, elle présente une possibilité alimentaire" ),
        
        Espece(title: "Cymodocea", latitude: 44.222544, longitude: 8.696063, subTitle: "Cymodocea nadosa", pic: "cymodocea", type: .flore, fav: false, lieu:"Au large des côtes", desc: "Cymodocea est un genre de plantes monocotylédones sous-marines de la famille des Cymodoceaceae. Le nom générique Cymodocea dérive du grec « Cymodocé » (divinité marine qui fait partie des Néréides), pour qualifier une plante qui vit dans la mer.\n\nCe sont des plantes marines herbacées, vivaces, appartenant à la famille des Cymodoceaceae, dont les caractères distinctifs sont les suivants: Feuilles en forme de ruban, portant une gaine à leur base, une ligule à la jonction de la gaine et du limbe et dotées d'un grand nombre de cellules à tanin, Tige portant des feuilles à chaque nœud du rhizome, nervures foliaires longitudinales au nombre de 7 à 17." ),
        
        Espece(title: "L'Espingole", latitude: 43.172222, longitude: 6.608333, subTitle: "Contre torpilleur", pic: "espingole", type: .vestige, fav: false, lieu:"Un peu partout dans la meditérrannée", desc:"L’Espingole fut construit en 1900 par les chantiers havrais Augustin Normand. Long de 56 mètres sur 6 de large, il jaugeait 330 tonneaux. Sa propulsion était assurée par 2 moteurs de 2600 CV qui lui permettaient d’atteindre la vitesse de 27 nœuds. Son équipage comprenait 62 hommes. Le Contre-Torpilleur repose sur un fond de sable par 39 mètres de profondeur.\n\nL’Espingole peut être visitée en une seule fois sans aucun problème. Le courant est rarement fort, et la visibilité souvent excellente. La poupe est coupée du centre du navire. L’hélice est toujours présente mais très ensablée. Une petite partie des pales émerge encore. Entre la proue et la partie centrale du navire se trouve un gros chargement de briques étalé sur le sable. La silhouette de l’Espingole est celle d’un squelette de métal géant. La coque a en effet disparu laissant des tôles en arcs de cercles plantées dans le sable, ressemblant ainsi étrangement aux côtes d’une cage thoracique. On peut facilement et sans risque pénétrer dans les différentes parties de l’épave.\n\nOn visite ainsi la salle des machines, son énorme tuyauterie et les quartiers de l’équipage. Juste avant la proue on peut admirer les chaudières qui sont désormais couchées sur tribord. La chaîne qui devait permettre à l’Espingole de retrouver la surface est toujours visible. Le bordage de la proue a un peu mieux résisté au poids des ans que le reste du navire. Bien que n’étant plus visible, le chargement d’obus de 47 et 65 mm est toujours présent. Il reste quelques spécimens enfouis sous le sable de la proue. Mais gare aux amateurs, les obus n’ont jamais été neutralisés." ),
        
        Espece(title: "Le Michel C", latitude: 43.02, longitude: 6.146389, subTitle: "Vapeur de cabotage", pic: "michelC", type: .vestige, fav: false, lieu:"Large de hyères", desc:"Le Michel C a coulé sur bâbord au sommet d’une roche, à environ 100 m d’une autre épave le Ville De Grasse. L’épave n’est pas très grande et très abîmée. Une plongée est suffisante pour en faire le tour, d’autant que la profondeur n’est pas très importante.\n\nLa partie la mieux conservée est la proue située à 39 m, où l’on peut encore admirer les treuils, ancres et grues de Capon. Sur la proue un énorme homard est caché dans les tôles. On retrouve les congres, amateurs de trous, sur la proue et au centre de l’épave vers la partie machine. De nombreuses murènes se cachent dans les multiples cachettes qu’offre le Michel C. Un Mérou se trouve parfois sur la proue.\n\nEn regardant dans le bleu on peut apercevoir des bancs de loups et de mulets. A l’inverse d’autres épaves de cette même côte, le Michel C n’est pas colonisé par les gorgones." ),
        
        Espece(title: "Le Wildcat", latitude: 43.270833, longitude: 6.404167, subTitle: "Chasseur", pic: "wildcat", type: .vestige, fav: false, lieu:"Le Lavandou", desc:"Le Wildcat F4-F était un chasseur américain qui fut produit par la firme américaine Grumman à environ 8.000 exemplaires. Il fut également construit en Grande-Bretagne avant la seconde Guerre Mondiale sous l’appellation de Martlet Mark V. L’avion repose sur le sable à la profondeur de 53 m.\n\nLa visibilité est souvent excellente sur le site, et on peut apercevoir l’épave dès 30-35 m. Comme toujours sur les épaves, il est bien de s’arrêter un instant pour contempler la silhouette du Wildcat. L’appareil est à l’envers, le cockpit ouvert dans le sable. Les ailes sont toutes les deux présentes et en bon état, tout comme le fuselage (qui a conservé la roue arrière) et l’empennage. Seul le nez du Wildcat est abîmé. Le moteur n’est pas visible, il ne reste que des câbles et tôles tordues. L’hélice a encore toutes ses palesLa flore est très peu présente.\n\nLa faune est représentée par des galathées. On peut en voir au moins 5 sous l’empennage à côté de l’hélice. De même de petites langoustes sont cachés dans les trous du fuselage. Un gros congre est dissimulé dans l’aile, tout comme de jolies petites rascasses rouges. Sous les ailes on retrouve les inévitables rougets. Si on a de la chance on pourra apercevoir un très gros homard, habitué des lieux." ),
        
        Espece(title: "Olbia", latitude: 43.079501, longitude: 6.123944, subTitle: "Cité greco-romaine", pic: "olbia", type: .vestige, fav: true , lieu:"Hyères vestige terre et mer", desc:"Les vestiges du quai romain font face au site archéologique d'Olbia, forteresse grecque devenue romaine. La ballade permet de déambuler au milieu d'énormes blocs de pierre.\n\nArrivé au bout du quai, on découvre une vaste étendue de blocs en vrac. Des traces d'assemblage comme des trous en queue d’aronde et des incrustations de plomb qui permettaient de tenir les blocs entre eux. Nous sommes sur le mole, zone de déchargement des navires. \n\nQuelques coups de palmes supplémentaires et nous sommes au-dessus d'une Tartane. Elle a fait naufrage dans les années 1860, chargée de blocs de pierre massif et aujourd'hui encore bien rangés. 3 mètres de fond : pas besoin de descendre pour admirer cette épave dont le bois est encore visible à l'arrière. De retour vers la plage, le paléo-tombolo, socle rocheux qui abrite une vie très riche." ),
        
        Espece(title: "Bar", latitude: 43.613204, longitude: 7.152355, subTitle: "Pseudotolithus", pic: "bar", type: .faune, fav: false, lieu:"Toute la meditérrannée", desc:"Bar est un nom vernaculaire ambigu désignant en français certains poissons, essentiellement de la famille des Moronidés.\n\nLe terme de « bar » désigne principalement deux espèces : le bar commun (Dicentrarchus labrax) et le bar tacheté (Dicentrarchus punctatus). Le mot « bar » vient du germanique bars, ce qui veut dire pointe, en référence aux dangereuses épines dorsales de ce poisson. Le bar commun est surnommé « loup » ou « perche de mer », dans la région méditerranéenne.\n\nCependant, les mots bar et loup ne sont pas complètement synonymes puisque loup désigne aussi les poissons du genre Anarhichas, qui sont eux uniquement appelés loups." ),
        
        Espece(title: "Marcel", latitude: 43.085505, longitude:  6.187829, subTitle: "Large de Hyères", pic: "marcel", type: .vestige, fav: false, lieu:"Large de hyères", desc:"Le Marcel, cargo de 42 mètres de long, entra en collision avec La Durance le 27 octobre 1895. Celle-ci le percuta sur tribord avant, entrainant son naufrage. La totalité de l’équipage put être sauvé par La Durance.\n\nLa plongée a lieu sur des fonds vaseux qui sont assez tristes. Les vestiges du Marcel sont peu identifiables. Néanmoins, l’étrave à guibre est caractéristique. Le pont et les superstructures ont disparus." ),
        
        Espece(title: "Mustang", latitude:  43.030026, longitude: 6.121661, subTitle: "Sud de l'aeroport de hyères", pic: "mustang", type: .vestige, fav: false , lieu:"Large de hyères", desc: "L’avion gît sur une profondeur de 56 mètres, posé à plat sur un fond de sable. C’est une épave réservée aux plongeurs expérimentés. Une plongée sur le site est largement suffisante. Il aurait été remorqué accidentellement par un chalut, ce qui expliquerait son état.\n\nDe ce qui fût le fleuron de la chasse alliée, il ne reste que l’avant dont l’hélice, et les ailes qui bien que rongées par la rouille conservent toujours leurs mitrailleuses. L’intérêt principal de cette épave est le cockpit (n°4 et 5) qui est en excellent état.\n\nNotre épave reste un mystère, car il n’y a aucune certitude quant à sa présence sous l’eau. L’avion fût vraisemblablement abattu par la D.C.A allemande au moment des opérations du Débarquement de Provence." ),
        
        Espece(title: "Prophète", latitude: 43.157501, longitude:  6.622633, subTitle: " La Croix-Valmer", pic: "prophete", type: .vestige, fav: true, lieu:"En dessous de Ramatuelle", desc:"Construit artisanalement à Sète en 1853 par l’atelier Reynaud et Cie, le Prophète mesurait 41,5 mètres de long pour 7,4 mètres de large et jaugeait 199 tonneaux. Il disposait d’une voilure auxiliaire. Il a coulé fin mars 1860 suite à une voie d’eau. La cargaison de blé qu’il transportait fut perdue. Le site n’est protégé d’aucun vent.\n\nLe Prophète a sombré sur un fond de sable entouré de posidonie par 34 mètres de fond. La forme du bateau est difficilement identifiable car la coque et le pont se sont ouverts à plat sur le sable. Cette épave est surnommée « les Chaudières » par certains. En effet celles-ci représentent la seule partie intéressante et relativement bien conservée du Prophète. Elles se trouvent au centre de l’épave.\n\nOn peut y voir également un énorme volant de forme ronde. Juste après la machinerie, en direction de la poupe, une énorme bobine repose sur le sable. Cette pièce est à l'origine du surnom de « Câblier » attribué par d’autres. Le reste est constitué de belles pièces réparties sur la proue et la poupe. Proue: les ancres à jas et le treuil. Poupe: le gouvernail et l’hélice à pales triangulaire." ),
        
        Espece(title: "Tromblon", latitude: 43.06801, longitude: 5.890199, subTitle: "Saint-Mandrier", pic: "tromblon", type: .vestige, fav: true, lieu:"Large de Toulon", desc:"Le Tromblon était une chaloupe-canonnière à hélice mise en service en 1875 à Toulon. Petit bâtiment en fer, il mesurait 23,67 m de long et 7,44 m de large, et jaugeait 189 tonneaux. Propulsé par une machine à vapeur de 450 CV, il atteignait 9 noeuds à 180 Tr/min. Son effectif était de 25 personnes. La petite canonnière consommait 5.250 kg de charbon par jour !\n\nLe 13 août 1898 il est proposé comme cible d'exercice, et c'est le 21 octobre de cette même année qu'il est conduit dans l'Anse des Sablettes. Deux des huit obus de 240 mm tirés sur lui depuis la batterie de Peyras l'atteignent, et mettent fin à sa courte carrière. Le Tromblon repose légèrement sur le côté droit, posé sur un fond sableux. L'épave a conservé sa forme générale. La proue (à droite du schéma) est extrêmement délabrée, certainement à cause de l'impact qui l'a coulé. Il subsiste quatre bossoirs, deux sur bâbord et deux sur tribord. Ne cherchez pas les canons, l'épave avant d'être coulée, a été démilitarisée. La coque est en mauvais état, trouée de part en part. Les deux chaudières sont encore entières. La cheminée est visible, couchée sur le flancs tribord. Du pont il ne reste que les traverses entre lesquelles on peut facilement passer. La poupe est complète.\n\nIl est intéressant de s'en écarter un peu pour contempler sa forme atypique. Les hélices, bien que présentes, sont ensablées dans leur presque totalité. Les épontilles (colonne verticale en fer qui soutient le pont) servent de repère à quelques congres et murènes et des bancs de sars s'y protègent parfois. Quelques rougets se baladents sur le sable environnant. Peu de gorgones et d'algues." ),
        
        Espece(title: "Lockheed", latitude: 43.191667, longitude: 5.716944, subTitle: "Saint-Cyr en mer", pic: "lockheed", type: .vestige, fav: true, lieu:"Saint-Cyr en mer", desc:"Il escorte des B-17 de la 97e US AIR FORCE, lorsque les Allemands attaquent la formation et le descendent. Cinquante deux ans plus tard en novembre 1996, Marcel Camilleri, Directeur du Club de plongée « Lecques Aquanaut Center » retrouve l’épave.\n\nLes fuselages de l’appareil (droit, gauche et central) sont en assez bon état. Il en est de même pour le cockpit. Celui-ci contient toujours le siège du pilote, ainsi que le tableau de bord ses instruments. Le nez de l’épave est légèrement enfoncé dans le sable, mais conserve ses canons. Le train d’atterrissage est rentré avec ses volets ouverts. Les moteurs sont couverts d’éponges et de spirographe.\n\nOn trouve quelques coraux sur le fuselage. Un congre a trouvé refuge dans le cockpit. La plupart de la faune de Méditerranée est présente sur le site: mostelles, chapons, homards…" ),
        
        Espece(title: "Raie-aigle vachette", latitude: 43.384205 , longitude:  4.399366, subTitle: "Pteromylaeus bovinus", pic: "raie", type: .faune, fav: false, lieu:"Toute la Meditérranée", desc: "Aetomylaeus bovinus espèce de raie de l'Atlantique, la Méditerranée et la mer Noire, au museau long et plat, à la queue fine dotée d'aiguillons venimeux, et aux bandes dorsales transversales.\n\nCette raie, considérée comme assez rare dans les eaux de Corse, tendrait à s’y rassembler au printemps. Elle est parfois également nommée Mourine vachette. Elle se caractérise par des pectorales pointues formant un disque losangique d’une coloration brun-verdâtre rayée de 7 ou de 9 bandes transversales sombres. Ce caractère distinctif permet de la différentier de l’aigle commun (Myliobatis aquila), dont le patron est uniforme. La face ventrale est claire. La tête forme une sorte de rostre saillant, dont elle se sert pour fouir les zones sableuses. Son envergure maximale 1, 50 m ; sa longueur de 2 m." ),
        
        Espece(title: "La Corse", latitude: 42.741168, longitude: 9.004271, subTitle: "Parcours faune", pic: "corse", type: .parcours, fav: false, lieu:"Large de la Corse", desc:"A Decouvrir au large de la Corse : dauphin, rascasse, castagnole, sardine\n \n \nCe parcours au large de Hyères permettra aux plongeurs de découvrir plusieurs espèces locales d'animaux.\n\nIl sera indispensable aux plongeurs débutants de passer par des professionnels afin de garantir leurs sécurité!"),
        
        Espece(title: "Hyeres", latitude: 43.029394, longitude: 6.117421, subTitle: "Parcours Vestige", pic: "hyeres", type: .parcours, fav: true, lieu:"Large de Hyères", desc:"Vestige a découvrir : Mustang, Michel C, Marcel. \n \n \n Ce parcours au large de Hyères permettra aux plongeurs de découvrir plusieurs carcasses de bateaux et avions.\n\nIl sera indispensable aux plongeurs débutants de passer par des professionnels afin de garantir leurs sécurité!"),
        
        Espece(title: "Nice", latitude: 43.683385, longitude: 7.323874, subTitle: "Parcours flore", pic: "nice", type: .parcours, fav: false, lieu:"Large de Nice", desc:"A Découvrir au large de Nice : padine, posedonie, carpodesmia\n \n \nCe parcours au large de Hyères permettra aux plongeurs de découvrir la flore locale, les espèces sont facilement identifiables grace aux descriptions.\n\nPour la découverte de la flore sous-marine il sera indispensable aux plongeurs débutants de passer par des professionnels afin de garantir leurs sécurité!"),
    ]
    
    
    
    
    
    static var faune : [ Espece ] {
        especes.filter { $0.type == .faune}
        
    }
    static var flore : [ Espece ] {
        especes.filter { $0.type == .flore}
        
    }
    static var vestige : [ Espece ] {
        especes.filter { $0.type == .vestige}
        
    }
    static var parcours : [ Espece ] {
        especes.filter { $0.type == .parcours}
        
    }
}

